<?php
/* SOLUTIONS / INDUSTRY — Software  (modelled on propellerads.com/solutions/software) */
$base = '';
$pageTitle = 'Software Campaigns — OOVA Ads';
require __DIR__ . '/includes/header.php';

$benefits = [
    ['Traffic for any software', 'Media players, antiviruses, browsers or other tools — we have the audience for it.'],
    ['Accurate targeting', 'Granular GEO, device, OS and interest targeting to reach engaged, ready-to-install users.'],
    ['Auto-optimization', 'CPA Goal and AI bidding lower your CPA and scale winning campaigns automatically.'],
    ['Anti-fraud protected', 'Multi-layer filtration means you pay for real installs, not non-human activity.'],
];
$stats = [
    ['x4', 'Higher CR than the previous year'],
    ['45%', 'Software revenue generated by US & Germany'],
    ['84%', 'Of software campaigns use Onclick traffic'],
    ['x4', 'Lower CPA with CPA Goal'],
];
?>
<section class="section solhero">
    <div class="container solhero__grid">
        <div class="solhero__text">
            <span class="eyebrow">Software</span>
            <h1>The right audience for your <span class="tx-green">Software</span> campaigns</h1>
            <p class="lead">Whether we're talking about media players, antiviruses, browsers, or other software, we have the traffic for it! Along with tools to accurately target your campaign, and reach engaged audiences.</p>
            <div class="solhero__actions">
                <a href="https://panel.oovaads.com/login" class="btn btn--primary">Start now →</a>
                <a href="index.php#formats" class="btn btn--ghost">Explore ad formats</a>
            </div>
        </div>
        <div class="solhero__media">
            <img src="img/software-hero.svg" alt="Software campaign audience targeting on OOVA Ads">
        </div>
    </div>
</section>

<section class="section">
    <div class="container">
        <div class="about-stats__grid">
            <?php foreach ($stats as [$num, $label]): ?>
                <div class="statcard statcard--light"><b><?= $num ?></b><span><?= $label ?></span></div>
            <?php endforeach; ?>
        </div>
    </div>
</section>

<section class="section section--tint">
    <div class="container">
        <div class="section-head section-head--center">
            <span class="eyebrow">Why software choose OOVA</span>
            <h2>Reach engaged audiences and lower your CPA</h2>
        </div>
        <div class="sol-grid">
            <?php foreach ($benefits as [$title, $desc]): ?>
                <div class="why-card">
                    <h3><?= $title ?></h3>
                    <p><?= $desc ?></p>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</section>

<section class="section cta">
    <div class="container">
        <h2>Grow your software campaigns with OOVA Ads</h2>
        <p>The right audience, accurate targeting and auto-optimization to lower your CPA — start in minutes.</p>
        <div style="display:flex; gap:14px; justify-content:center; flex-wrap:wrap;">
            <a href="https://panel.oovaads.com/login" class="btn btn--light">Start now →</a>
            <a href="contact.php" class="btn btn--white-outline">Talk to us</a>
        </div>
    </div>
</section>

<?php require __DIR__ . '/includes/footer.php'; ?>
